spring.application.name=Personal-Finance-App


spring.datasource.url=jdbc:postgresql://localhost:5432/personal_finance_db
spring.datasource.username=postgres
spring.datasource.password=154545!%$%$%
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=false

jwt.secret=ZmMyNzViZjE0NzQ0ODQ4Y2E0YjM4NzdlYzI1YzIwOTQzNmJjOTU1NjNmYmEwOTZkYjEzZmYxZDA5MTcwZGIxOA==
jwt.access-token-expiration-ms=900000
jwt.refresh-token-expiration-ms=604800000